ARG NODE_VERSION=16.15.0
FROM node:${NODE_VERSION}

RUN echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list \
&& apt-get update \
&& apt-get install -y zip vim less man tcpdump jq net-tools libcap2-bin \
&& apt-get install -y ghostscript poppler-utils libjpeg62-turbo libopenjp2-7-dev unzip unrar-free libreoffice python3-crypto python3-requests python3-requests-futures python3-crypto python3-rarfile python3-magic python3-pip \
&& pip3 install Pillow \
&& apt-get install -y -t stretch-backports git \
&& echo "root:password" | chpasswd

WORKDIR /home/node/src/atomic-fishbowl-server
